# Generated by Django 3.2 on 2021-10-24 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GMF', '0002_auto_20211017_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('poster', models.ImageField(upload_to='media')),
                ('category', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Offer_poster',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=600)),
                ('poster', models.ImageField(upload_to='media')),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_desc',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('color_available', models.CharField(max_length=30000)),
                ('desc_query', models.CharField(max_length=10000)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_new',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=5000)),
                ('price', models.IntegerField(default=0)),
                ('off', models.FloatField(default=0.0)),
                ('mrp', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Products_type',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('poster', models.ImageField(upload_to='media')),
                ('type', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='product_new',
            name='Product_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='GMF.products_type'),
        ),
        migrations.AddField(
            model_name='product_new',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='GMF.category'),
        ),
        migrations.AddField(
            model_name='product_new',
            name='desc',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='GMF.product_desc'),
        ),
        migrations.AddField(
            model_name='product_new',
            name='offers',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='GMF.offer_poster'),
        ),
        migrations.AddField(
            model_name='product_new',
            name='size',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='GMF.sizes'),
        ),
    ]
