# Generated by Django 3.2 on 2021-10-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMF', '0003_auto_20211024_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_new',
            name='size',
            field=models.CharField(max_length=3000),
        ),
        migrations.DeleteModel(
            name='Sizes',
        ),
    ]
