# Generated by Django 3.2 on 2021-10-24 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GMF', '0004_auto_20211024_1035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_new',
            new_name='Products',
        ),
    ]
