# Generated by Django 3.2 on 2021-10-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMF', '0005_rename_product_new_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_type',
            name='title',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
