# Generated by Django 3.2 on 2021-11-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMF', '0008_address_auth_user_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='avatar.jpg', upload_to='media'),
        ),
    ]
