# Generated by Django 3.2 on 2021-12-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMF', '0010_auto_20211204_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='poster',
            field=models.ImageField(default='/ntg/', upload_to='media'),
        ),
    ]
