# Generated by Django 3.2 on 2022-02-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMF', '0014_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='desc',
        ),
        migrations.AddField(
            model_name='products',
            name='desc',
            field=models.ManyToManyField(default='', to='GMF.Product_desc'),
        ),
    ]
